# Generated by Django 3.1.2 on 2020-10-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepost', '0003_auto_20201005_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtable',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
