# Generated by Django 3.1.2 on 2020-10-05 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imagepost', '0004_auto_20201005_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewTable',
            new_name='ImageTable',
        ),
    ]
